export const styles = {
  container: {
    width: '100%',
    // minHeight: '100vh', // Removed to avoid double scrollbars
    backgroundColor: 'transparent', // Let dashboard background show through
    padding: '0',
  },
  
  // HR Notice
  hrNotice: {
    background: '#eff6ff', 
    padding: 16, 
    borderRadius: 12, 
    border: '1px solid #bfdbfe',
    display: 'flex', 
    gap: 12, 
    alignItems: 'flex-start', 
    margin: '0 0 24px 0',
  },
  
  // Main Tab Navigation
  mainTabContainer: {
    display: 'flex',
    gap: '4px',
    backgroundColor: 'transparent',
    padding: '0 0 16px 0',
    borderBottom: '1px solid #e2e8f0',
    marginBottom: '24px',
  },
  mainTabButton: {
    padding: '10px 20px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#64748b',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    borderRadius: '8px',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  mainTabButtonActive: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
  },
  
  // Tab Content
  tabContent: {
    backgroundColor: 'transparent',
    padding: '0',
    animation: 'fadeIn 0.3s ease-in-out',
  },
  
  // Toolbar
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    gap: '16px',
  },
  toolbarLeft: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    flex: 1,
  },
  toolbarRight: {
    display: 'flex',
    gap: '12px',
  },
  createBtn: {
    padding: '10px 20px',
    backgroundColor: '#3b82f6', // Blue-500
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.2s',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    boxShadow: '0 2px 4px rgba(59, 130, 246, 0.2)',
  },
  filterSelect: {
    padding: '9px 14px',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    fontSize: '14px',
    backgroundColor: 'white',
    cursor: 'pointer',
    color: '#475569',
    outline: 'none',
  },
  searchInput: {
    flex: 1,
    maxWidth: '320px',
    padding: '9px 14px',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  iconBtn: {
    padding: '10px',
    backgroundColor: 'white',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '16px',
    color: '#64748b',
    transition: 'all 0.2s',
  },
  
  // View Mode Tabs
  viewModeTabs: {
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
    marginBottom: '20px',
    padding: '4px',
    backgroundColor: '#f1f5f9',
    borderRadius: '10px',
    width: 'fit-content',
  },
  viewModeTab: {
    padding: '6px 14px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#64748b',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    borderRadius: '8px',
    transition: 'all 0.2s',
    whiteSpace: 'nowrap',
  },
  viewModeTabActive: {
    backgroundColor: 'white',
    color: '#0f172a',
    fontWeight: '600',
    boxShadow: '0 1px 2px rgba(0,0,0,0.05)',
  },
  viewModeDivider: {
    width: '1px',
    height: '16px',
    backgroundColor: '#cbd5e1',
    margin: '0 8px',
  },
  
  // Table
  tableWrapper: {
    backgroundColor: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
    border: '1px solid #f1f5f9',
    minHeight: '300px',
  },
  loadingContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '64px 20px',
    gap: '16px',
  },
  loadingText: {
    fontSize: '14px',
    color: '#64748b',
    fontWeight: '500',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  th: {
    padding: '16px 24px',
    textAlign: 'left',
    backgroundColor: '#f8fafc',
    color: '#475569',
    fontWeight: '600',
    fontSize: '13px',
    borderBottom: '1px solid #e2e8f0',
    whiteSpace: 'nowrap',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  tr: {
    borderBottom: '1px solid #f1f5f9',
    transition: 'background-color 0.2s',
  },
  td: {
    padding: '16px 24px',
    color: '#334155',
    verticalAlign: 'middle',
  },
  
  // Badges & Cells
  statusBadge: {
    padding: '6px 12px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '600',
    display: 'inline-flex',
    alignItems: 'center',
  },
  deadlineBadge: {
    padding: '4px 10px',
    backgroundColor: '#f1f5f9',
    color: '#475569',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '500',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
  },
  userBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  avatar: {
    width: '32px',
    height: '32px',
    borderRadius: '12px',
    backgroundColor: '#3b82f6',
    color: 'white',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '600',
    boxShadow: '0 2px 4px rgba(59, 130, 246, 0.15)',
  },
  projectBadge: {
    padding: '4px 10px',
    backgroundColor: '#eff6ff',
    color: '#2563eb',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '600',
  },
  keyBadge: {
    padding: '4px 8px',
    backgroundColor: '#f8fafc',
    color: '#64748b',
    border: '1px solid #e2e8f0',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '700',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
  },
  descriptionCell: {
    maxWidth: '260px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '13px',
    color: '#64748b',
  },
  
  // Footer
  tableFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 24px',
    backgroundColor: 'white',
    borderTop: '1px solid #f1f5f9',
  },
  
  // Performance Tab
  performanceHeader: {
    marginBottom: '24px',
    padding: '24px',
    backgroundColor: 'white',
    borderRadius: '16px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    border: '1px solid #f1f5f9',
  },
  summaryCards: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '24px',
    marginBottom: '24px',
  },
  summaryCard: {
    backgroundColor: 'white',
    borderRadius: '16px',
    padding: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05)',
    border: '1px solid #f1f5f9',
    transition: 'transform 0.2s',
    cursor: 'default',
  },
  summaryIcon: {
    fontSize: '24px',
    width: '56px',
    height: '56px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: '14px',
    color: '#475569',
  },
  summaryValue: {
    fontSize: '32px',
    fontWeight: '700',
    color: '#0f172a',
    lineHeight: '1',
    marginTop: '4px',
  },
  summaryLabel: {
    fontSize: '14px',
    color: '#64748b',
    fontWeight: '600',
  },
  
  // Progress Bar
  progressBar: {
    flex: 1,
    height: '8px',
    backgroundColor: '#f1f5f9',
    borderRadius: '4px',
    overflow: 'hidden',
    minWidth: '100px',
  },
};
