export const styles = {
  container: {
    width: '100%',
    minHeight: '100vh',
    backgroundColor: '#f0f2f5',
    padding: '0',
  },
  
  // Main Tab Navigation
  mainTabContainer: {
    display: 'flex',
    gap: '2px',
    backgroundColor: '#d4d9e1',
    padding: '4px',
    borderRadius: '8px 8px 0 0',
  },
  mainTabButton: {
    padding: '12px 24px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#4a5568',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    borderRadius: '6px',
    transition: 'all 0.2s',
  },
  mainTabButtonActive: {
    backgroundColor: '#f0f2f5',
    color: '#2d3748',
    fontWeight: '600',
  },
  
  // Tab Content
  tabContent: {
    backgroundColor: '#f0f2f5',
    padding: '16px',
  },
  
  // Toolbar
  toolbar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
    gap: '12px',
  },
  toolbarLeft: {
    display: 'flex',
    gap: '12px',
    alignItems: 'center',
    flex: 1,
  },
  toolbarRight: {
    display: 'flex',
    gap: '8px',
  },
  createBtn: {
    padding: '8px 16px',
    backgroundColor: '#10b981',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  filterSelect: {
    padding: '8px 12px',
    border: '1px solid #cbd5e0',
    borderRadius: '6px',
    fontSize: '14px',
    backgroundColor: 'white',
    cursor: 'pointer',
  },
  searchInput: {
    flex: 1,
    maxWidth: '300px',
    padding: '8px 12px',
    border: '1px solid #cbd5e0',
    borderRadius: '6px',
    fontSize: '14px',
  },
  iconBtn: {
    padding: '8px 12px',
    backgroundColor: 'white',
    border: '1px solid #cbd5e0',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  
  // View Mode Tabs
  viewModeTabs: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
    marginBottom: '12px',
    padding: '8px 12px',
    backgroundColor: 'white',
    borderRadius: '8px',
    flexWrap: 'wrap',
  },
  viewModeTab: {
    padding: '6px 12px',
    border: 'none',
    backgroundColor: 'transparent',
    color: '#4a5568',
    fontSize: '13px',
    cursor: 'pointer',
    borderRadius: '4px',
    transition: 'all 0.2s',
    whiteSpace: 'nowrap',
  },
  viewModeTabActive: {
    backgroundColor: '#e2e8f0',
    color: '#2d3748',
    fontWeight: '500',
  },
  viewModeDivider: {
    width: '1px',
    height: '20px',
    backgroundColor: '#cbd5e0',
  },
  settingsBtn: {
    padding: '6px 12px',
    border: '1px solid #cbd5e0',
    backgroundColor: 'white',
    color: '#4a5568',
    fontSize: '13px',
    cursor: 'pointer',
    borderRadius: '4px',
    whiteSpace: 'nowrap',
  },
  
  // Table
  tableWrapper: {
    backgroundColor: 'white',
    borderRadius: '8px',
    overflow: 'auto',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    minHeight: '200px',
  },
  loadingContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '64px 20px',
  },
  loadingText: {
    fontSize: '16px',
    color: '#64748b',
    fontWeight: '500',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '14px',
  },
  th: {
    padding: '12px 16px',
    textAlign: 'left',
    backgroundColor: '#f7fafc',
    color: '#4a5568',
    fontWeight: '600',
    fontSize: '13px',
    borderBottom: '2px solid #e2e8f0',
    whiteSpace: 'nowrap',
  },
  tr: {
    borderBottom: '1px solid #e2e8f0',
    transition: 'background-color 0.2s',
  },
  td: {
    padding: '12px 16px',
    color: '#2d3748',
  },
  sortIcon: {
    marginLeft: '4px',
    fontSize: '10px',
    color: '#a0aec0',
  },
  starBtn: {
    border: 'none',
    background: 'transparent',
    fontSize: '18px',
    cursor: 'pointer',
    color: '#cbd5e0',
  },
  
  // Task/Project specific
  taskName: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  taskIcon: {
    color: '#a0aec0',
  },
  projectName: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  projectIcon: {
    fontSize: '12px',
  },
  deadlineBadge: {
    padding: '4px 10px',
    backgroundColor: '#e0f2fe',
    color: '#0369a1',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: '500',
  },
  userBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  avatar: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: '#10b981',
    color: 'white',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    fontWeight: '600',
  },
  projectBadge: {
    padding: '4px 10px',
    backgroundColor: '#dbeafe',
    color: '#1e40af',
    borderRadius: '12px',
    fontSize: '12px',
  },
  keyBadge: {
    padding: '4px 8px',
    backgroundColor: '#f1f5f9',
    color: '#475569',
    borderRadius: '4px',
    fontSize: '12px',
    fontWeight: '600',
    fontFamily: 'monospace',
  },
  descriptionCell: {
    maxWidth: '200px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: '13px',
    color: '#64748b',
  },
  performanceBadge: {
    padding: '4px 10px',
    backgroundColor: '#dcfce7',
    color: '#166534',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: '500',
  },
  membersGroup: {
    display: 'flex',
    gap: '4px',
  },
  memberAvatar: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: '#3b82f6',
    color: 'white',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '11px',
    fontWeight: '600',
    border: '2px solid white',
  },
  roleBadge: {
    padding: '4px 10px',
    backgroundColor: '#fef3c7',
    color: '#92400e',
    borderRadius: '4px',
    fontSize: '12px',
  },
  privacyBadge: {
    padding: '4px 10px',
    backgroundColor: '#e0e7ff',
    color: '#3730a3',
    borderRadius: '4px',
    fontSize: '12px',
  },
  
  // Footer
  tableFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '12px 16px',
    backgroundColor: 'white',
    marginTop: '1px',
    borderRadius: '0 0 8px 8px',
    fontSize: '13px',
    color: '#4a5568',
    fontWeight: '600',
  },
  footerLeft: {
    display: 'flex',
    gap: '8px',
  },
  footerCenter: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  footerRight: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  pageSize: {
    padding: '4px 8px',
    border: '1px solid #cbd5e0',
    borderRadius: '4px',
    fontSize: '13px',
  },
  paginationBtn: {
    padding: '6px 12px',
    border: '1px solid #cbd5e0',
    backgroundColor: 'white',
    borderRadius: '4px',
    fontSize: '13px',
    cursor: 'pointer',
    fontWeight: '500',
  },
  
  // Action Buttons
  actionButtons: {
    display: 'flex',
    gap: '12px',
    marginTop: '12px',
  },
  actionBtnActive: {
    padding: '10px 24px',
    backgroundColor: '#3b82f6',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  actionBtn: {
    padding: '10px 24px',
    backgroundColor: 'white',
    color: '#4a5568',
    border: '1px solid #cbd5e0',
    borderRadius: '6px',
    fontSize: '13px',
    fontWeight: '500',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
  },
}
